[build]
target = "i686-none.json"
rustflags = ["-Clink-args=-Tros.ld", "-Cforce-frame-pointers", "-Zsymbol-mangling-version=v0"]

[unstable]
build-std = ["core", "alloc"]

[target.i686-none]
runner = "./qemu.sh"
